env:
  matrix:
    secure: "svs48By1j3bZ3ORlcNoRMPKcEkj6mqRa07FYxXtoFv7FVWLbjp3GfRdJUooXDgzL0xikw+1P57JWCObQpYBZInCg+WpV6YtXya0NQq4NmbaP6VUq/DzAk8CL4PoXQnH269y2u9QVnpJ5w2Wgpr2AaKeSPNMJ761haBhXoAHv0UDwNmL6CEjt67ZAd/C/BaJtBED3/HsZgjERBxAUrY23wDM25escZrs6JmYUvN511AEuMjftL7DqyQ7zzYJCmUXcEdergwkqjxwruZwu3G6ifoZlHphhJxNVAKRunuwTj87JjHR8S1BF5yLdjfnoL26Ue8PmMhkoyqpzqeAxYsAhPeIbIU+W/1uRZYfI1BxNY58PN5s2Rt5kqsHq/JsyKP/vdShT2bMhVQgeYPgoY/+teSWDrtBIho3LGvOFl0G+5MMvOTy6P/yc4+khti9Q9cX+TZvipR2jYuxyKnduc2o0po8FmyC3RK3KwlMVxfOAbhoZHUmK+8Yp5nnRt4UXL2scLRw1ORysPL58pLEaAWkSs0i5mDzTeTPL0ihp4/C0NZCubwDg/ybuZEZfW/RnSP1Inst/6BL7kZ68k3nsH9PRzd7XUUgKlaw7s2dR/W0qGxw56+oxn8OUDQakMEqBWfgMGazJ+1rZpaEAGb+2lqwYP5q7e/bUdJjgZuCz5TmW7s0="
language: java

addons:
  sonarcloud:
    organization: "sankarvijay-github"
    token:
    secure: "QyLNB8Rp3nn9tyrGjsPRl+Dq6Gfjeje/tvi75i07r1tRhUiVzb7rcXK36m8sLIo60FUkZobjpNzQEjTuoYjrY9WfgMw5/KfZPJCxM1rdr9HvAaA2rnD6xItdte647Bnmwy+d/aXU6LvMlZzJOE+oc4Kbwh6dIH4w4TpmKLS2h5ih/A6SPWeA5uPCUJONjqXjHI4JwJmTfzt7vy+7YpzrfNTME3JaZi97qqu1/GWZ4+u+ZW4AGzbl+3VtcLTXolfAAREsRa4KKuWCkHT4QrIOmU5CLdTDYbwQW/NDGuWYqk64cQJxa4/T20eQ5NNpjbEqxlk1MxoZKwi8h4/OunvBBnJIJ8l44xp5HP4ncRVDWziMztxKoW27QWquTsHehgUL1aeM6ZvEuDvo61sSx1OeK+VSQgWs2Fb7DSwmug64MLj1fPKGMMfSPteLuP4IOLiwUp78J/WtbLMwZEsGR+Trudh2PsuWBA1POYWIdejIXDgVwJAjI6NrtMYxRj1DDYbuWqxfzl1w0Lfnn2pWmQorDsZFx2JdJu1NUW5SJ6o6EbpQruL0VTdh3hfsuc20h0TzeQf5JLZtXhs6NE4LY8hw1CvMhlv+1++W+z7ceT29GrPzchTyCbWUz5C758XC02n75n8B7odoPXdpBIMIuOahxUHBNU2U6qCsW6JP+9e5yC4="
sudo: false

jdk:
  - oraclejdk8

before_install:
# does not seem to work anymore on April, 3rd, 2017 (JPM down?)
#  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
#  - java -jar jpm4j.jar -u init
#  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

script:
  - ./gradlew check jacocoTestReport coveralls sendCoverageToCodacy
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner

after_success:
# does not seem to work anymore on April, 3rd, 2017 (JPM down?)
#  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml



cache:
  directories:
    - '$HOME/.sonar/cache'
